Add examples
ballerina-platform/module-ballerinax-openai.finetunes pull request #12
Opened 2024-08-14 10:10 UTC by KATTA-00

## Purpose

- Added two example with these documentations
- Updated a README.md for examples

2024-08-14 14:44 UTC, NipunaRanasinghe requested changes

2024-08-14 14:44 UTC, NipunaRanasinghe commented on ballerina/Ballerina.toml
> +version = "1.0.7"
lets revert this version update

2024-08-14 14:44 UTC, NipunaRanasinghe commented on examples/Sarcastic-bot/Ballerina.toml
> +name = "Sports_headline_analyzer"
```suggestion
name = "sarcastic_bot"
```

2024-08-14 14:44 UTC, NipunaRanasinghe commented on examples/Sarcastic-bot/Ballerina.toml
> +org = "kanishka"
We usually use the `wso2` as the orgname for the examples
```suggestion
org = "wso2"
```

2024-08-14 14:44 UTC, NipunaRanasinghe commented on examples/Sarcastic-bot/Ballerina.toml
> +repository = "local"
lets remove this

2024-08-14 14:44 UTC, NipunaRanasinghe commented on examples/Sarcastic-bot/Dependencies.toml
Usually we don't commit the `Dependencies.toml` file for the examples. So we can remove this too

2024-08-14 14:44 UTC, NipunaRanasinghe commented on examples/Sarcastic-bot/main.bal
> +string validationFilePath = "./data/" + validationFileName;
```suggestion
const SERVICE_URL = "https://api.openai.com/v1";
const TRAINING_FILENAME = "training.jsonl";
const VALIDATION_FILENAME = "validation.jsonl";
const TRAINING_FILEPATH = "./data/" + trainingFileName;
const VALIDATION_FILEPATH = "./data/" + validationFileName;
```

2024-08-14 14:44 UTC, NipunaRanasinghe commented on examples/Sports-headline-analyzer/Ballerina.toml
> +name = "Sports_headline_analyzer"
```suggestion
name = "sports_headline_analyzer"
```

2024-08-14 14:44 UTC, NipunaRanasinghe commented on examples/Sports-headline-analyzer/main.bal
> +    if (fineTuneJob.status != "succeeded") {
```suggestion
    if fineTuneJob.status != "succeeded" {
```

2024-08-14 14:44 UTC, NipunaRanasinghe commented on examples/Sports-headline-analyzer/main.bal
> +    if (deleteFileResponse.deleted == true) {
```suggestion
    if (deleteFileResponse.deleted) {
```

2024-08-14 14:44 UTC, NipunaRanasinghe commented on examples/Sports-headline-analyzer/Ballerina.toml
> +org = "kanishka"
```suggestion
org = "wso2"
```

2024-08-14 15:59 UTC, KATTA-00 commented on examples/Sarcastic-bot/Ballerina.toml
> +repository = "local"
noted

2024-08-14 16:00 UTC, KATTA-00 commented on examples/Sarcastic-bot/Dependencies.toml
noted

2024-08-14 16:28 UTC, NipunaRanasinghe commented on examples/README.md
> +1. Generate a API as described in the [Setup guide](https://central.ballerina.io/ballerinax/openai.finetunes/latest#setup-guide).
```suggestion
1. Generate an API key as described in the [Setup guide](https://central.ballerina.io/ballerinax/openai.finetunes/latest#setup-guide).
```

2024-08-14 16:28 UTC, NipunaRanasinghe commented on examples/Sarcastic-bot/.gitignore
Do we need this .gitignore as we already have one under the repository root?

2024-08-14 16:28 UTC, NipunaRanasinghe commented on examples/Sports-headline-analyzer/Sports headline analyzer.md
> +## Sports Headlines Analyzer
We should use title case in all the headers. Please fix all the similar places
```suggestion
## Sports headlines analyzer
```

2024-08-14 16:28 UTC, NipunaRanasinghe commented on examples/Sports-headline-analyzer/Sports headline analyzer.md
> +## Run the Example
ditto
```suggestion
## Run the example
```

2024-08-14 17:05 UTC, KATTA-00 commented on examples/Sarcastic-bot/.gitignore
No, I think, it was automatically generated when creating a project. let me remove them

2024-08-14 17:24 UTC, NipunaRanasinghe requested changes

2024-08-14 17:24 UTC, NipunaRanasinghe commented on examples/Sarcastic-bot/Sarcastic bot.md
> +## Sarcastic Bot
```suggestion
## Sarcastic bot
```

2024-08-14 17:24 UTC, NipunaRanasinghe commented on README.md
> +1. [Sarcastic Bot](https://github.com/ballerina-platform/module-ballerinax-openai.finetunes/tree/main/examples/Sarcastic-bot) - Fine-tune the GPT-3.5-turbo model to generate sarcastic responses
```suggestion
1. [Sarcastic bot](https://github.com/ballerina-platform/module-ballerinax-openai.finetunes/tree/main/examples/Sarcastic-bot) - Fine-tune the GPT-3.5-turbo model to generate sarcastic responses 
```

2024-08-14 17:24 UTC, NipunaRanasinghe commented on README.md
> +2. [Sports Headline Analyzer](https://github.com/ballerina-platform/module-ballerinax-openai.finetunes/tree/main/examples/Sports-headline-analyzer) - Fine-tune the GPT-4o-mini model to extract struct
```suggestion
2. [Sports headline analyzer](https://github.com/ballerina-platform/module-ballerinax-openai.finetunes/tree/main/examples/Sports-headline-analyzer) - Fine-tune the GPT-4o-mini model to extract structured information (player, team, sport, and gender) from sports headlines.
```

2024-08-14 17:24 UTC, NipunaRanasinghe commented on README.md
> -[//]: # (TODO: Add examples)
Need to update the same in the `Module.md` and `Package.md` as well

2024-08-15 04:34 UTC, NipunaRanasinghe approved these changes, later dismissed

2024-08-15 04:35 UTC, NipunaRanasinghe commented on ballerina/Dependencies.toml
> +version = "1.0.7"
```suggestion
version = "1.0.5"
```

2024-08-15 04:35 UTC, NipunaRanasinghe commented on ballerina/Dependencies.toml
> +version = "2.11.0"
```suggestion
version = "2.12.1"
```

2024-08-15 04:35 UTC, NipunaRanasinghe approved these changes
LGTM

2024-08-15 04:50 UTC, merged